language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'

script:
  - nosetests
  #  We are not doing the tests below yet due to errors
  #  - ( cd systest && python ./systest.py -t /tmp -c )
